name: screen_loader
description: Easy to use mixin ScreenLoader, which will handle the loading on the screen. You can customise the loading as well.
version: 1.1.0
homepage: https://github.com/arnold-parge/screen_loader

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
